name: Generate Daily Puzzle

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run generate:daily
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: add daily puzzle"
          file_pattern: puzzles/*.json
