name: Generate Daily Puzzle

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Run generator
        run: npm run generate:daily 2>&1 | tee daily.log
      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: daily-puzzle-logs
          path: daily.log
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: add daily puzzle"
          file_pattern: puzzles/*.json
